server:
  port: 8081
  servlet.context-path: /mishap

spring:
  security: 
    user: 
      name: user1
      password: mypass

springdoc.api-docs.enabled: false

logging.level:
  org.apache.catalina.loader.WebappClassLoaderBase: ERROR

---
spring:
  profiles: devel

  security: 
    user: 
      name: user2
      password: test

# logging.level.de.dicos.dcsspring.config.PropertyRefresher: DEBUG
  
---
spring:
  profiles: e2e

app:
  dummy.login.active: true


---
spring:
  profiles: test

springdoc.api-docs.enabled: true

# logging.level.org.apache.http.headers: DEBUG
# logging.level.org.apache.http.wire: DEBUG

# logging.level:
#  de.dicos.smlib.db.base.AppDbUpdater: DEBUG

